const pages=[['dashboard','Overview'],['command','Command Center'],['products','Products'],['approvals','Approvals'],['audit','Audit Log'],['connection','Amazon Connection'],['security','Security Center']];let state={page:'dashboard',preview:null};
const app=document.querySelector('#app'),nav=document.querySelector('#nav');
function toast(msg){const x=document.querySelector('#toast');x.textContent=msg;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2500)}
async function api(url,options={}){const r=await fetch(url,{headers:{'Content-Type':'application/json'},...options});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Request failed');return data}
function money(v){return v==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'EGP'}).format(v)}
function setPage(p){state.page=p;location.hash=p;render();}
nav.innerHTML=pages.map(([id,label])=>`<button class="nav" data-page="${id}">${label}</button>`).join('');nav.onclick=e=>{const b=e.target.closest('[data-page]');if(b)setPage(b.dataset.page)};
async function health(){try{const h=await api('/api/health');document.querySelector('#health').textContent=`Database online • v${h.version}`;document.querySelector('#health').style.color='#38d58c'}catch{document.querySelector('#health').textContent='Database unavailable';document.querySelector('#health').style.color='#ff5964'}}
function hero(title,sub,action=''){return `<div class="hero"><div><h1>${title}</h1><div class="muted">${sub}</div></div>${action}</div>`}
async function dashboard(){const d=await api('/api/dashboard');app.innerHTML=hero('Operations overview','Real data stored in Railway PostgreSQL',`<button class="btn primary" onclick="setPage('command')">Create product</button>`)+`<div class="grid"><div class="card kpi"><span>Products</span><strong>${d.products}</strong></div><div class="card kpi"><span>Variants</span><strong>${d.variants}</strong></div><div class="card kpi"><span>Pending approvals</span><strong>${d.pendingApprovals}</strong></div><div class="card kpi"><span>Audit events</span><strong>${d.auditEvents}</strong></div></div><div class="card panel"><h3>Safety state</h3><p>Simulation Mode: <b>${d.simulationMode?'ON':'OFF'}</b></p><p>Emergency Lock: <b>${d.emergencyLock?'ACTIVE':'OFF'}</b></p><p class="muted">This release stores product operations in PostgreSQL. Live Amazon publishing is deliberately disabled.</p></div>`}
async function command(){app.innerHTML=hero('Product Command Center','Create a persistent Parent and all Children from Arabic or English')+`<div class="two"><div class="card"><label>Product command</label><textarea id="cmd">Create SKU CK1 men's shoes, colors Black Grey White, sizes from 41 to 45, price 499 EGP, origin Egypt, FBA</textarea><div class="toolbar" style="margin-top:12px"><button class="btn" id="previewBtn">Preview</button><button class="btn primary" id="createBtn">Create draft</button></div></div><div class="card"><h3>Parsed preview</h3><div id="parsed" class="preview muted">Click Preview.</div></div></div>`;document.querySelector('#previewBtn').onclick=async()=>{try{state.preview=await api('/api/commands/preview',{method:'POST',body:JSON.stringify({command:document.querySelector('#cmd').value})});document.querySelector('#parsed').textContent=JSON.stringify(state.preview,null,2)}catch(e){toast(e.message)}};document.querySelector('#createBtn').onclick=async()=>{try{const r=await api('/api/commands/create',{method:'POST',body:JSON.stringify({command:document.querySelector('#cmd').value})});toast(`${r.product.parent_sku} saved with ${r.parsed.variants.length} variants`);setPage('products')}catch(e){toast(e.message)}}}
async function products(){const rows=await api('/api/products');app.innerHTML=hero('Products','Drafts and variants stored in PostgreSQL',`<button class="btn primary" onclick="setPage('command')">New product</button>`)+`<div class="card"><table><thead><tr><th>Parent SKU</th><th>Product</th><th>Variants</th><th>Price</th><th>Validation</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${r.parent_sku}</b></td><td>${r.product_name}<br><small class="muted">${r.gender||''} • ${r.fulfillment}</small></td><td>${r.variant_count}</td><td>${money(r.price)}</td><td><span class="status ${r.validation_status}">${r.validation_status}</span></td><td><span class="status ${r.status}">${r.status}</span></td><td><button class="btn" onclick="validateProduct(${r.id})">Validate</button></td></tr>`).join('')||'<tr><td colspan="7" class="muted">No products yet.</td></tr>'}</tbody></table></div>`}
window.validateProduct=async id=>{try{const r=await api(`/api/products/${id}/validate`,{method:'POST'});toast(`Validation ${r.status}: ${r.issues.length} issues`);products()}catch(e){toast(e.message)}};
async function approvals(){const rows=await api('/api/approvals');app.innerHTML=hero('Approvals','Reviewer decisions persisted in PostgreSQL')+`<div class="card"><table><thead><tr><th>Product</th><th>Action</th><th>Validation</th><th>Status</th><th>Decision</th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${r.parent_sku}</b><br><small>${r.product_name}</small></td><td>${r.action}</td><td>${r.validation_status}</td><td><span class="status ${r.status}">${r.status}</span></td><td>${r.status==='PENDING'?`<button class="btn good" onclick="decide(${r.id},'APPROVED')">Approve</button> <button class="btn bad" onclick="decide(${r.id},'REJECTED')">Reject</button>`:'Reviewed by '+(r.reviewed_by||'—')}</td></tr>`).join('')||'<tr><td colspan="5">No approvals.</td></tr>'}</tbody></table></div>`}
window.decide=async(id,decision)=>{try{await api(`/api/approvals/${id}/decision`,{method:'POST',body:JSON.stringify({decision})});toast(`Approval ${decision.toLowerCase()}`);approvals()}catch(e){toast(e.message)}};
async function audit(){const rows=await api('/api/audit');app.innerHTML=hero('Audit Log','Immutable operational history in PostgreSQL')+`<div class="card"><table><thead><tr><th>Date</th><th>Actor</th><th>Action</th><th>Entity</th><th>Details</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${new Date(r.created_at).toLocaleString()}</td><td>${r.actor}</td><td>${r.action}</td><td>${r.entity_type} ${r.entity_id||''}</td><td><small>${JSON.stringify(r.details)}</small></td></tr>`).join('')||'<tr><td colspan="5">No audit events.</td></tr>'}</tbody></table></div>`}
function connection(){app.innerHTML=hero('Amazon Connection','Foundation is configured; credentials are not displayed')+`<div class="grid"><div class="card"><span>Marketplace</span><h2>Amazon Egypt</h2><small>ARBP9OOSHTCHU</small></div><div class="card"><span>SP-API endpoint</span><h3>EU endpoint</h3><small>Configured in Railway Variables</small></div><div class="card"><span>Connection</span><h2>Not authorized</h2><small>LWA credentials are intentionally absent</small></div><div class="card"><span>Publish</span><h2 style="color:#ff5964">Blocked</h2><small>Simulation + Emergency Lock</small></div></div><div class="card panel"><h3>Next secure step</h3><p>Create a private SP-API app, authorize it in Seller Central, and store credentials only in Railway Variables. Do not paste credentials into this interface.</p></div>`}
function security(){app.innerHTML=hero('Security Center','Production safety controls')+`<div class="grid"><div class="card"><h3>Emergency Lock</h3><p style="color:#38d58c">ACTIVE</p></div><div class="card"><h3>Simulation Mode</h3><p style="color:#38d58c">ON</p></div><div class="card"><h3>Database</h3><p style="color:#38d58c">PostgreSQL</p></div><div class="card"><h3>Credentials</h3><p>Server variables only</p></div></div><div class="card panel"><h3>Publishing rule</h3><p>Creator → Validation → Reviewer → Publisher → Amazon. This version stops before Amazon publishing.</p></div>`}
async function render(){document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.page===state.page));try{if(state.page==='dashboard')await dashboard();else if(state.page==='command')await command();else if(state.page==='products')await products();else if(state.page==='approvals')await approvals();else if(state.page==='audit')await audit();else if(state.page==='connection')connection();else security()}catch(e){app.innerHTML=`<div class="card"><h2>Unable to load</h2><p>${e.message}</p><p class="muted">Check Railway deployment logs and DATABASE_URL.</p></div>`}}
state.page=location.hash.slice(1)||'dashboard';window.addEventListener('hashchange',()=>{state.page=location.hash.slice(1)||'dashboard';render()});health();render();
